version: '3.3'
services:
  grafana:
    image: grafana/grafana
    user: "472"
    tty: true
    depends_on:
      - prometheus
    ports:
      - 3000:3000    
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=123456
      - GF_USERS_ALLOW_SIGN_UP=false
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards

